name: 'venv setup'
description: 'configures venv, python and caches'

inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax."
    required: true
  requirement-files:
    description: "Requirement files to install. Can be a glob pattern."
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984  # v4.3.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Setup action variables
      id: venv
      shell: bash
      run: |
        python3 -uS ${{ github.action_path }}/bin/setup-venv vars \
        --python-version ${{ inputs.python-version }} \
        --requirement-files-hash ${{ hashFiles(inputs.requirement-files) }}

    - uses: actions/cache@v3
      id: cache-venv
      with:
        path: ${{ steps.venv.outputs.venv-dir }}
        key: ${{ steps.venv.outputs.cache-key }}

    - run: python3 -m venv ${{ steps.venv.outputs.venv-dir }}
      if: steps.cache-venv.outputs.cache-hit != 'true'
      shell: bash

    - run: |
        source ${{ steps.venv.outputs.venv-dir }}/bin/activate
        echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV
      shell: bash

     - run: echo "cache-hit=${{ steps.cache-venv.outputs.cache-hit }}" >> $GITHUB_OUTPUT
      shell: bash
