name: 'venv setup'
description: 'configures venv, python and caches'

inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax."
    default: 3.8.13
  requirement-files:
    description: "Requirement files to install. Can be a glob pattern."
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup python
      uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984  # v4.3.0
      with:
        python-version: ${{ inputs.python-version }}

    - run: echo "${{ inputs.requirement-files }} -> ${{ hashFiles(inputs.requirement-files) }}"
      shell: bash

    - name: Make venv
      id: venv
      shell: bash
      run: |
        python3 -uS ${{ github.action_path }}/bin/setup-venv \
        --python-version ${{ inputs.python-version }} \
        --requirement-files-hash ${{ hashFiles(inputs.requirement-files) }}

    # - name: Pip install

    # - name: Cache venv
