name: Self Test

on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test action-setup-venv
      uses: ./
      with:
        python-version: 3.8.13
        requirement-files: test/testdata/requirements.txt
    - name: Ensure environment works
      run: python3 ./test/testdata/demo.py
