name: Self Test

on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run local action
      uses: ./
      with:
        requirement-files: test/testdata/requirements.txt
    - name: Run demo
      run: python3 ./test/testdata/demo.py
