name: Self Test

on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test action-setup-venv
      id: venv
      uses: ./
      with:
        python-version: 3.8.13
        install-cmd: pip install -r test/testdata/requirements.txt
    - name: Print variables for debugging
      run: |
        echo "VIRTUAL_ENV: ${VIRTUAL_ENV}"
        echo "PATH: ${PATH}"
        echo "Cache Hit: ${{ steps.venv.outputs.cache-hit }}"
      shell: bash
    - name: Print site-packages for debugging
      run:  ls -la ${VIRTUAL_ENV}/lib/*/site-packages/
    - name: Ensurenvironment works
      run: python3 ./test/testdata/demo.py

